// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo8CsmBG9HBiDj9iCe6kibBepyD1IKY70',
    appId: '1:276511700686:web:4147db6fa580f44b3a029f',
    messagingSenderId: '276511700686',
    projectId: 'taskflow-9dbec',
    authDomain: 'taskflow-9dbec.firebaseapp.com',
    storageBucket: 'taskflow-9dbec.firebasestorage.app',
    measurementId: 'G-C6G3BGYFPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4KCe9xkOxa3GTQrF-C8RAGTve8tinOdQ',
    appId: '1:276511700686:android:22847a996298d3f83a029f',
    messagingSenderId: '276511700686',
    projectId: 'taskflow-9dbec',
    storageBucket: 'taskflow-9dbec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn-2dEJOHpEm6Eedh5Scw2w1KedhuVRGE',
    appId: '1:276511700686:ios:1ead5bf7cc1faf803a029f',
    messagingSenderId: '276511700686',
    projectId: 'taskflow-9dbec',
    storageBucket: 'taskflow-9dbec.firebasestorage.app',
    iosBundleId: 'com.example.taskFlowManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn-2dEJOHpEm6Eedh5Scw2w1KedhuVRGE',
    appId: '1:276511700686:ios:1ead5bf7cc1faf803a029f',
    messagingSenderId: '276511700686',
    projectId: 'taskflow-9dbec',
    storageBucket: 'taskflow-9dbec.firebasestorage.app',
    iosBundleId: 'com.example.taskFlowManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo8CsmBG9HBiDj9iCe6kibBepyD1IKY70',
    appId: '1:276511700686:web:027fb13a3e16c1f13a029f',
    messagingSenderId: '276511700686',
    projectId: 'taskflow-9dbec',
    authDomain: 'taskflow-9dbec.firebaseapp.com',
    storageBucket: 'taskflow-9dbec.firebasestorage.app',
    measurementId: 'G-P56RJ6RYYK',
  );
}
